server:
  port: 8082
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:whtdb
    driver-className: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
solace:
  queueName: tpc
  jms:
    host: smf://localhost:55554
    msgVpn: default
    clientUsername: admin
    clientPassword: admin
---
